/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"net/http"

	"github.com/5g-core/openapi"
	. "github.com/5g-core/openapi/models"
	"github.com/5g-core/udr/logger"
	. "github.com/5g-core/udr/producer"
	"github.com/gin-gonic/gin"
)

// ReadIPTVCongifurationData - Retrieve IPTV configuration Data
func HttpReadIPTVCongifurationData(c *gin.Context) {
	logger.HandlerLog.Infof("ReadIPTVCongifurationData is called")
    /// <param name="configIds type: []string">Each element identifies a configuration. (optional)</param>
    /// <param name="dnns type: []string">Each element identifies a DNN. (optional)</param>
    /// <param name="snssais type: []Snssai">Each element identifies a slice. (optional)</param>
    /// <param name="supis type: []string">Each element identifies the user. (optional)</param>
    /// <param name="interGroupIds type: []string">Each element identifies a group of users. (optional)</param>
	// Getting query params 
	queryParams := c.Request.URL.Query()
	// query parameter : basename config-ids paramName configIds
	configIds := queryParams[""]
	// query parameter : basename dnns paramName dnns
	dnns := queryParams[""]
	// query parameter : basename snssais paramName snssais
	snssais := queryParams[""]
	// query parameter : basename supis paramName supis
	supis := queryParams[""]
	// query parameter : basename inter-group-ids paramName interGroupIds
	interGroupIds := queryParams[""]
	rsp := HandleReadIPTVCongifurationData( configIds,dnns,snssais,supis,interGroupIds, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}
