/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"net/http"

	"github.com/5g-core/openapi"
	. "github.com/5g-core/openapi/models"
	"github.com/5g-core/udr/logger"
	. "github.com/5g-core/udr/producer"
	"github.com/gin-gonic/gin"
)

// DeleteIndividualInfluenceDataSubscription - Delete an individual Influence Data Subscription resource
func HttpDeleteIndividualInfluenceDataSubscription(c *gin.Context) {
	logger.HandlerLog.Infof("DeleteIndividualInfluenceDataSubscription is called")
    /// <param name="subscriptionId type: string">String identifying a subscription to the Individual Influence Data Subscription</param>
    // Getting the path params
	subscriptionId :=c.Params.ByName("subscriptionId")
	rsp := HandleDeleteIndividualInfluenceDataSubscription( subscriptionId, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}

// ReadIndividualInfluenceDataSubscription - Get an existing individual Influence Data Subscription resource
func HttpReadIndividualInfluenceDataSubscription(c *gin.Context) {
	logger.HandlerLog.Infof("ReadIndividualInfluenceDataSubscription is called")
    /// <param name="subscriptionId type: string">String identifying a subscription to the Individual Influence Data Subscription</param>
    // Getting the path params
	subscriptionId :=c.Params.ByName("subscriptionId")
	rsp := HandleReadIndividualInfluenceDataSubscription( subscriptionId, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}

// ReplaceIndividualInfluenceDataSubscription - Modify an existing individual Influence Data Subscription resource
func HttpReplaceIndividualInfluenceDataSubscription(c *gin.Context) {
	logger.HandlerLog.Infof("ReplaceIndividualInfluenceDataSubscription is called")
    /// <param name="subscriptionId type: string">String identifying a subscription to the Individual Influence Data Subscription</param>
    /// <param name="trafficInfluSub type: TrafficInfluSub"></param>
    // Getting the path params
	subscriptionId :=c.Params.ByName("subscriptionId")
	// get and parse body
	var trafficInfluSub TrafficInfluSub
	if err := getDataFromRequestBody(c, &trafficInfluSub); err != nil {
		problemDetail := "[Request Body] " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
	}
	rsp := HandleReplaceIndividualInfluenceDataSubscription( subscriptionId,trafficInfluSub, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}
