/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"net/http"

	"github.com/5g-core/openapi"
	. "github.com/5g-core/openapi/models"
	"github.com/5g-core/udr/logger"
	. "github.com/5g-core/udr/producer"
	"github.com/gin-gonic/gin"
)

// CreateIndividualInfluenceDataSubscription - Create a new Individual Influence Data Subscription resource
func HttpCreateIndividualInfluenceDataSubscription(c *gin.Context) {
	logger.HandlerLog.Infof("CreateIndividualInfluenceDataSubscription is called")
    /// <param name="trafficInfluSub type: TrafficInfluSub"></param>
	// get and parse body
	var trafficInfluSub TrafficInfluSub
	if err := getDataFromRequestBody(c, &trafficInfluSub); err != nil {
		problemDetail := "[Request Body] " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
	}
	rsp := HandleCreateIndividualInfluenceDataSubscription( trafficInfluSub, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}

// ReadInfluenceDataSubscriptions - Read Influence Data Subscriptions
func HttpReadInfluenceDataSubscriptions(c *gin.Context) {
	logger.HandlerLog.Infof("ReadInfluenceDataSubscriptions is called")
    /// <param name="dnn type: string">Identifies a DNN. (optional)</param>
    /// <param name="snssai type: Snssai">Identifies a slice. (optional)</param>
    /// <param name="internalGroupId type: string">Identifies a group of users. (optional)</param>
    /// <param name="supi type: string">Identifies a user. (optional)</param>
	// Getting query params 
	queryParams := c.Request.URL.Query()
	// query parameter : basename dnn paramName dnn
	dnn := queryParams[""]
	// query parameter : basename snssai paramName snssai
	snssai := queryParams[""]
	// query parameter : basename internal-Group-Id paramName internalGroupId
	internalGroupId := queryParams[""]
	// query parameter : basename supi paramName supi
	supi := queryParams[""]
	rsp := HandleReadInfluenceDataSubscriptions( dnn,snssai,internalGroupId,supi, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}
