/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"net/http"

	"github.com/5g-core/openapi"
	. "github.com/5g-core/openapi/models"
	"github.com/5g-core/udr/logger"
	. "github.com/5g-core/udr/producer"
	"github.com/gin-gonic/gin"
)

// CreateOrReplaceIndividualPFDData - Create or update the corresponding PFDs for the specified application identifier
func HttpCreateOrReplaceIndividualPFDData(c *gin.Context) {
	logger.HandlerLog.Infof("CreateOrReplaceIndividualPFDData is called")
    /// <param name="appId type: string">Indicate the application identifier for the request pfd(s). It shall apply the format of Data type ApplicationId.</param>
    /// <param name="pfdDataForAppExt type: PfdDataForAppExt"></param>
    // Getting the path params
	appId :=c.Params.ByName("appId")
	// get and parse body
	var pfdDataForAppExt PfdDataForAppExt
	if err := getDataFromRequestBody(c, &pfdDataForAppExt); err != nil {
		problemDetail := "[Request Body] " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
	}
	rsp := HandleCreateOrReplaceIndividualPFDData( appId,pfdDataForAppExt, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}

// DeleteIndividualPFDData - Delete the corresponding PFDs of the specified application identifier
func HttpDeleteIndividualPFDData(c *gin.Context) {
	logger.HandlerLog.Infof("DeleteIndividualPFDData is called")
    /// <param name="appId type: string">Indicate the application identifier for the request pfd(s). It shall apply the format of Data type ApplicationId.</param>
    // Getting the path params
	appId :=c.Params.ByName("appId")
	rsp := HandleDeleteIndividualPFDData( appId, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}

// ReadIndividualPFDData - Retrieve the corresponding PFDs of the specified application identifier
func HttpReadIndividualPFDData(c *gin.Context) {
	logger.HandlerLog.Infof("ReadIndividualPFDData is called")
    /// <param name="appId type: string">Indicate the application identifier for the request pfd(s). It shall apply the format of Data type ApplicationId.</param>
    // Getting the path params
	appId :=c.Params.ByName("appId")
	rsp := HandleReadIndividualPFDData( appId, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}
