/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"net/http"

	"github.com/5g-core/openapi"
	. "github.com/5g-core/openapi/models"
	"github.com/5g-core/udr/logger"
	. "github.com/5g-core/udr/producer"
	"github.com/gin-gonic/gin"
)

// CreateSMFSubscriptions - Create SMF Subscription Info
func HttpCreateSMFSubscriptions(c *gin.Context) {
	logger.HandlerLog.Infof("CreateSMFSubscriptions is called")
    /// <param name="ueId type: string"></param>
    /// <param name="subsId type: string"></param>
    /// <param name="smfSubscriptionInfo type: SmfSubscriptionInfo"></param>
    // Getting the path params
	ueId :=c.Params.ByName("ueId")
	subsId :=c.Params.ByName("subsId")
	// get and parse body
	var smfSubscriptionInfo SmfSubscriptionInfo
	if err := getDataFromRequestBody(c, &smfSubscriptionInfo); err != nil {
		problemDetail := "[Request Body] " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
	}
	rsp := HandleCreateSMFSubscriptions( ueId,subsId,smfSubscriptionInfo, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}

// GetSmfSubscriptionInfo - Retrieve SMF Subscription Info
func HttpGetSmfSubscriptionInfo(c *gin.Context) {
	logger.HandlerLog.Infof("GetSmfSubscriptionInfo is called")
    /// <param name="ueId type: string"></param>
    /// <param name="subsId type: string"></param>
    // Getting the path params
	ueId :=c.Params.ByName("ueId")
	subsId :=c.Params.ByName("subsId")
	rsp := HandleGetSmfSubscriptionInfo( ueId,subsId, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}

// ModifySmfSubscriptionInfo - Modify SMF Subscription Info
func HttpModifySmfSubscriptionInfo(c *gin.Context) {
	logger.HandlerLog.Infof("ModifySmfSubscriptionInfo is called")
    /// <param name="ueId type: string"></param>
    /// <param name="subsId type: string"></param>
    /// <param name="patchItem type: []PatchItem"></param>
    /// <param name="supportedFeatures type: string">Features required to be supported by the target NF (optional)</param>
    // Getting the path params
	ueId :=c.Params.ByName("ueId")
	subsId :=c.Params.ByName("subsId")
	// Getting query params 
	queryParams := c.Request.URL.Query()
	// query parameter : basename supported-features paramName supportedFeatures
	supportedFeatures := queryParams[""]
	// get and parse body
	var patchItem []PatchItem
	if err := getDataFromRequestBody(c, &patchItem); err != nil {
		problemDetail := "[Request Body] " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
	}
	rsp := HandleModifySmfSubscriptionInfo( ueId,subsId,patchItem,supportedFeatures, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}

// RemoveSmfSubscriptionsInfo - Delete SMF Subscription Info
func HttpRemoveSmfSubscriptionsInfo(c *gin.Context) {
	logger.HandlerLog.Infof("RemoveSmfSubscriptionsInfo is called")
    /// <param name="ueId type: string"></param>
    /// <param name="subsId type: string"></param>
    // Getting the path params
	ueId :=c.Params.ByName("ueId")
	subsId :=c.Params.ByName("subsId")
	rsp := HandleRemoveSmfSubscriptionsInfo( ueId,subsId, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}
