/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"net/http"

	"github.com/5g-core/openapi"
	. "github.com/5g-core/openapi/models"
	"github.com/5g-core/udr/logger"
	. "github.com/5g-core/udr/producer"
	"github.com/gin-gonic/gin"
)

// CreateOrReplaceIndividualInfluenceData - Create or update an individual Influence Data resource
func HttpCreateOrReplaceIndividualInfluenceData(c *gin.Context) {
	logger.HandlerLog.Infof("CreateOrReplaceIndividualInfluenceData is called")
    /// <param name="influenceId type: string">The Identifier of an Individual Influence Data to be created or updated. It shall apply the format of Data type string.</param>
    /// <param name="trafficInfluData type: TrafficInfluData"></param>
    // Getting the path params
	influenceId :=c.Params.ByName("influenceId")
	// get and parse body
	var trafficInfluData TrafficInfluData
	if err := getDataFromRequestBody(c, &trafficInfluData); err != nil {
		problemDetail := "[Request Body] " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
	}
	rsp := HandleCreateOrReplaceIndividualInfluenceData( influenceId,trafficInfluData, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}

// DeleteIndividualInfluenceData - Delete an individual Influence Data resource
func HttpDeleteIndividualInfluenceData(c *gin.Context) {
	logger.HandlerLog.Infof("DeleteIndividualInfluenceData is called")
    /// <param name="influenceId type: string">The Identifier of an Individual Influence Data to be updated. It shall apply the format of Data type string.</param>
    // Getting the path params
	influenceId :=c.Params.ByName("influenceId")
	rsp := HandleDeleteIndividualInfluenceData( influenceId, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}

// UpdateIndividualInfluenceData - Modify part of the properties of an individual Influence Data resource
func HttpUpdateIndividualInfluenceData(c *gin.Context) {
	logger.HandlerLog.Infof("UpdateIndividualInfluenceData is called")
    /// <param name="influenceId type: string">The Identifier of an Individual Influence Data to be updated. It shall apply the format of Data type string.</param>
    /// <param name="trafficInfluDataPatch type: TrafficInfluDataPatch"></param>
    // Getting the path params
	influenceId :=c.Params.ByName("influenceId")
	// get and parse body
	var trafficInfluDataPatch TrafficInfluDataPatch
	if err := getDataFromRequestBody(c, &trafficInfluDataPatch); err != nil {
		problemDetail := "[Request Body] " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
	}
	rsp := HandleUpdateIndividualInfluenceData( influenceId,trafficInfluDataPatch, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}
