/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"net/http"

	"github.com/5g-core/openapi"
	. "github.com/5g-core/openapi/models"
	"github.com/5g-core/udr/logger"
	. "github.com/5g-core/udr/producer"
	"github.com/gin-gonic/gin"
)

// DeleteIndividualApplicationDataSubscription - Delete the individual Application Data subscription
func HttpDeleteIndividualApplicationDataSubscription(c *gin.Context) {
	logger.HandlerLog.Infof("DeleteIndividualApplicationDataSubscription is called")
    /// <param name="subsId type: string"></param>
    // Getting the path params
	subsId :=c.Params.ByName("subsId")
	rsp := HandleDeleteIndividualApplicationDataSubscription( subsId, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}

// ReadIndividualApplicationDataSubscription - Get an existing individual Application Data Subscription resource
func HttpReadIndividualApplicationDataSubscription(c *gin.Context) {
	logger.HandlerLog.Infof("ReadIndividualApplicationDataSubscription is called")
    /// <param name="subsId type: string">String identifying a subscription to the Individual Application Data Subscription</param>
    // Getting the path params
	subsId :=c.Params.ByName("subsId")
	rsp := HandleReadIndividualApplicationDataSubscription( subsId, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}

// ReplaceIndividualApplicationDataSubscription - Modify a subscription to receive notification of application data changes
func HttpReplaceIndividualApplicationDataSubscription(c *gin.Context) {
	logger.HandlerLog.Infof("ReplaceIndividualApplicationDataSubscription is called")
    /// <param name="subsId type: string"></param>
    /// <param name="applicationDataSubs type: ApplicationDataSubs"></param>
    // Getting the path params
	subsId :=c.Params.ByName("subsId")
	// get and parse body
	var applicationDataSubs ApplicationDataSubs
	if err := getDataFromRequestBody(c, &applicationDataSubs); err != nil {
		problemDetail := "[Request Body] " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
	}
	rsp := HandleReplaceIndividualApplicationDataSubscription( subsId,applicationDataSubs, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}
