/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"net/http"

	"github.com/5g-core/openapi"
	. "github.com/5g-core/openapi/models"
	"github.com/5g-core/udr/logger"
	. "github.com/5g-core/udr/producer"
	"github.com/gin-gonic/gin"
)

// GetGroupIdentifiers - Mapping of Group Identifiers
func HttpGetGroupIdentifiers(c *gin.Context) {
	logger.HandlerLog.Infof("GetGroupIdentifiers is called")
    /// <param name="extGroupId type: string">External Group Identifier (optional)</param>
    /// <param name="intGroupId type: string">Internal Group Identifier (optional)</param>
    /// <param name="ueIdInd type: bool">Indication whether UE identifiers are required or not (optional, default to false)</param>
    /// <param name="supportedFeatures type: string">Supported Features (optional)</param>
	// Getting query params 
	queryParams := c.Request.URL.Query()
	// query parameter : basename ext-group-id paramName extGroupId
	extGroupId := queryParams[""]
	// query parameter : basename int-group-id paramName intGroupId
	intGroupId := queryParams[""]
	// query parameter : basename ue-id-ind paramName ueIdInd
	ueIdInd := queryParams[""]
	// query parameter : basename supported-features paramName supportedFeatures
	supportedFeatures := queryParams[""]
	rsp := HandleGetGroupIdentifiers( extGroupId,intGroupId,ueIdInd,supportedFeatures, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}
