/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"net/http"

	"github.com/5g-core/openapi"
	. "github.com/5g-core/openapi/models"
	"github.com/5g-core/udr/logger"
	. "github.com/5g-core/udr/producer"
	"github.com/gin-gonic/gin"
)

// AmfContext3gpp - To modify the AMF context data of a UE using 3gpp access in the UDR
func HttpAmfContext3gpp(c *gin.Context) {
	logger.HandlerLog.Infof("AmfContext3gpp is called")
    /// <param name="ueId type: string">UE id</param>
    /// <param name="patchItem type: []PatchItem"></param>
    /// <param name="supportedFeatures type: string">Features required to be supported by the target NF (optional)</param>
    // Getting the path params
	ueId :=c.Params.ByName("ueId")
	// Getting query params 
	queryParams := c.Request.URL.Query()
	// query parameter : basename supported-features paramName supportedFeatures
	supportedFeatures := queryParams[""]
	// get and parse body
	var patchItem []PatchItem
	if err := getDataFromRequestBody(c, &patchItem); err != nil {
		problemDetail := "[Request Body] " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
	}
	rsp := HandleAmfContext3gpp( ueId,patchItem,supportedFeatures, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}

// CreateAmfContext3gpp - To store the AMF context data of a UE using 3gpp access in the UDR
func HttpCreateAmfContext3gpp(c *gin.Context) {
	logger.HandlerLog.Infof("CreateAmfContext3gpp is called")
    /// <param name="ueId type: string">UE id</param>
    /// <param name="amf3GppAccessRegistration type: Amf3GppAccessRegistration"></param>
    // Getting the path params
	ueId :=c.Params.ByName("ueId")
	// get and parse body
	var amf3GppAccessRegistration Amf3GppAccessRegistration
	if err := getDataFromRequestBody(c, &amf3GppAccessRegistration); err != nil {
		problemDetail := "[Request Body] " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
	}
	rsp := HandleCreateAmfContext3gpp( ueId,amf3GppAccessRegistration, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}

// QueryAmfContext3gpp - Retrieves the AMF context data of a UE using 3gpp access
func HttpQueryAmfContext3gpp(c *gin.Context) {
	logger.HandlerLog.Infof("QueryAmfContext3gpp is called")
    /// <param name="ueId type: string">UE id</param>
    /// <param name="fields type: []string">attributes to be retrieved (optional)</param>
    /// <param name="supportedFeatures type: string">Supported Features (optional)</param>
    // Getting the path params
	ueId :=c.Params.ByName("ueId")
	// Getting query params 
	queryParams := c.Request.URL.Query()
	// query parameter : basename fields paramName fields
	fields := queryParams[""]
	// query parameter : basename supported-features paramName supportedFeatures
	supportedFeatures := queryParams[""]
	rsp := HandleQueryAmfContext3gpp( ueId,fields,supportedFeatures, c)

	// send response
	for k, v := range rsp.Header {
		// TODO: concatenate all values
		c.Header(k, v[0])
	}
	serializedBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorf("Serialize Response Body error: %+v", err)
		problemDetail := "Serialize Response Body error: " + err.Error()
		var status int32
		status =int32(http.StatusBadRequest)
		title:="Malformed request syntax"
		rsp := ProblemDetails{
			Title:  &title,
			Status: &status,
			Detail: &problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusInternalServerError, rsp)
	} else {
		c.Data(rsp.Status, "application/json", serializedBody)
	}
}
