/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"net/http"

	"github.com/5g-core/logger_util"
	"github.com/5g-core/udr/logger"
	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
 type Route struct {
	 // Name is the name of this Route.
	 Name        string
	 // Method is the string for the HTTP method. ex) GET, POST etc..
	 Method      string
	 // Pattern is the pattern of the URI.
	 Pattern     string
	 // HandlerFunc is the handler function of this route.
	 HandlerFunc gin.HandlerFunc
 }
 
 // Routes is the list of the generated Route.
 type Routes []Route
 
 // NewRouter returns a new router.
 func NewRouter() *gin.Engine {
	 router := logger_util.NewGinWithLogrus(logger.GinLog)
	 AddService(router)
 
	 return router
 }
 
 // Index is the index handler.
 func Index(c *gin.Context) {
	 c.String(http.StatusOK, "Hello World!")
 }
 
 
 func AddService(engine *gin.Engine) *gin.RouterGroup {
	 group := engine.Group("/nudr-dr/v2")
	 for _, route := range routes {
		 switch route.Method {
		 case "GET":
			 group.GET(route.Pattern, route.HandlerFunc)
		 case "PATCH":
			 group.PATCH(route.Pattern, route.HandlerFunc)
		 case "POST":
			 group.POST(route.Pattern, route.HandlerFunc)
		 case "PUT":
			 group.PUT(route.Pattern, route.HandlerFunc)
		 case "DELETE":
			 group.DELETE(route.Pattern, route.HandlerFunc)
		 }
	 }
	 return group
 }
 
 
 var routes = Routes{
	 {
		 "Index",
		 http.MethodGet,
		 "/",
		 Index,
	 },
 
	 {
		 "HttpAmfContext3gpp",
		 http.MethodPatch,
		 "/subscription-data/:ueId/context-data/amf-3gpp-access",
		 HttpAmfContext3gpp,
	 },
 
	 {
		 "HttpCreateAmfContext3gpp",
		 http.MethodPut,
		 "/subscription-data/:ueId/context-data/amf-3gpp-access",
		 HttpCreateAmfContext3gpp,
	 },
 
	 {
		 "HttpQueryAmfContext3gpp",
		 http.MethodGet,
		 "/subscription-data/:ueId/context-data/amf-3gpp-access",
		 HttpQueryAmfContext3gpp,
	 },
 
	 {
		 "HttpAmfContextNon3gpp",
		 http.MethodPatch,
		 "/subscription-data/:ueId/context-data/amf-non-3gpp-access",
		 HttpAmfContextNon3gpp,
	 },
 
	 {
		 "HttpCreateAmfContextNon3gpp",
		 http.MethodPut,
		 "/subscription-data/:ueId/context-data/amf-non-3gpp-access",
		 HttpCreateAmfContextNon3gpp,
	 },
 
	 {
		 "HttpQueryAmfContextNon3gpp",
		 http.MethodGet,
		 "/subscription-data/:ueId/context-data/amf-non-3gpp-access",
		 HttpQueryAmfContextNon3gpp,
	 },
 /*
	 {
		 "HttpCreateAMFSubscriptions",
		 http.MethodPut,
		 "/subscription-data/:ueId/context-data/ee-subscriptions/:subsId/amf-subscriptions",
		 HttpCreateAMFSubscriptions,
	 },
 */
	 {
		 "HttpCreateOrReplaceAccessAndMobilityData",
		 http.MethodPut,
		 "/exposure-data/:ueId/access-and-mobility-data",
		 HttpCreateOrReplaceAccessAndMobilityData,
	 },
 
	 {
		 "HttpDeleteAccessAndMobilityData",
		 http.MethodDelete,
		 "/exposure-data/:ueId/access-and-mobility-data",
		 HttpDeleteAccessAndMobilityData,
	 },
 
	 {
		 "HttpQueryAccessAndMobilityData",
		 http.MethodGet,
		 "/exposure-data/:ueId/access-and-mobility-data",
		 HttpQueryAccessAndMobilityData,
	 },
 
	 {
		 "HttpUpdateAccessAndMobilityData",
		 http.MethodPatch,
		 "/exposure-data/:ueId/access-and-mobility-data",
		 HttpUpdateAccessAndMobilityData,
	 },
 
	 {
		 "HttpReadAccessAndMobilityPolicyData",
		 http.MethodGet,
		 "/policy-data/ues/:ueId/am-data",
		 HttpReadAccessAndMobilityPolicyData,
	 },
 
	 {
		 "HttpQueryAmData",
		 http.MethodGet,
		 "/subscription-data/:ueId/:servingPlmnId/provisioned-data/am-data",
		 HttpQueryAmData,
	 },
 
	 {
		 "HttpModifyAmfSubscriptionInfo",
		 http.MethodPatch,
		 "/subscription-data/:ueId/context-data/ee-subscriptions/:subsId/amf-subscriptions",
		 HttpModifyAmfSubscriptionInfo,
	 },
 
	 {
		 "HttpCreateIndividualApplicationDataSubscription",
		 http.MethodPost,
		 "/application-data/subs-to-notify",
		 HttpCreateIndividualApplicationDataSubscription,
	 },
 
	 {
		 "HttpReadApplicationDataChangeSubscriptions",
		 http.MethodGet,
		 "/application-data/subs-to-notify",
		 HttpReadApplicationDataChangeSubscriptions,
	 },
 
	 {
		 "HttpDeleteAuthenticationStatus",
		 http.MethodDelete,
		 "/subscription-data/:ueId/authentication-data/authentication-status",
		 HttpDeleteAuthenticationStatus,
	 },
 
	 {
		 "HttpQueryAuthenticationStatus",
		 http.MethodGet,
		 "/subscription-data/:ueId/authentication-data/authentication-status",
		 HttpQueryAuthenticationStatus,
	 },
 
	 {
		 "HttpQueryAuthSubsData",
		 http.MethodGet,
		 "/subscription-data/:ueId/authentication-data/authentication-subscription",
		 HttpQueryAuthSubsData,
	 },
 
	 {
		 "HttpCreateAuthenticationSoR",
		 http.MethodPut,
		 "/subscription-data/:ueId/ue-update-confirmation-data/sor-data",
		 HttpCreateAuthenticationSoR,
	 },
 
	 {
		 "HttpQueryAuthSoR",
		 http.MethodGet,
		 "/subscription-data/:ueId/ue-update-confirmation-data/sor-data",
		 HttpQueryAuthSoR,
	 },
 
	 {
		 "HttpCreateAuthenticationStatus",
		 http.MethodPut,
		 "/subscription-data/:ueId/authentication-data/authentication-status",
		 HttpCreateAuthenticationStatus,
	 },
 
	 {
		 "HttpModifyAuthenticationSubscription",
		 http.MethodPatch,
		 "/subscription-data/:ueId/authentication-data/authentication-subscription",
		 HttpModifyAuthenticationSubscription,
	 },
 
	 {
		 "HttpCreateAuthenticationUPU",
		 http.MethodPut,
		 "/subscription-data/:ueId/ue-update-confirmation-data/upu-data",
		 HttpCreateAuthenticationUPU,
	 },
 
	 {
		 "HttpQueryAuthUPU",
		 http.MethodGet,
		 "/subscription-data/:ueId/ue-update-confirmation-data/upu-data",
		 HttpQueryAuthUPU,
	 },
 
	 {
		 "HttpReadBdtData",
		 http.MethodGet,
		 "/policy-data/bdt-data",
		 HttpReadBdtData,
	 },
 
	 {
		 "HttpReadBdtPolicyData",
		 http.MethodGet,
		 "/application-data/bdtPolicyData",
		 HttpReadBdtPolicyData,
	 },
 
	 {
		 "HttpQueryCagAck",
		 http.MethodGet,
		 "/subscription-data/:ueId/ue-update-confirmation-data/subscribed-cag",
		 HttpQueryCagAck,
	 },
 
	 {
		 "HttpCreateCagUpdateAck",
		 http.MethodPut,
		 "/subscription-data/:ueId/ue-update-confirmation-data/subscribed-cag",
		 HttpCreateCagUpdateAck,
	 },
 
	 {
		 "HttpQuery5GVnGroupInternal",
		 http.MethodGet,
		 "/subscription-data/group-data/5g-vn-groups/internal",
		 HttpQuery5GVnGroupInternal,
	 },
 
	 {
		 "HttpQuery5GVnGroup",
		 http.MethodGet,
		 "/subscription-data/group-data/5g-vn-groups",
		 HttpQuery5GVnGroup,
	 },
 
	 {
		 "HttpCreate5GVnGroup",
		 http.MethodPut,
		 "/subscription-data/group-data/5g-vn-groups/:externalGroupId",
		 HttpCreate5GVnGroup,
	 },
 
	 {
		 "HttpQueryContextData",
		 http.MethodGet,
		 "/subscription-data/:ueId/context-data",
		 HttpQueryContextData,
	 },
 
	 {
		 "HttpCreateSharedData",
		 http.MethodPut,
		 "/subscription-data/shared-data/:sharedDataId",
		 HttpCreateSharedData,
	 },
 
	 {
		 "HttpDelete5GVnGroup",
		 http.MethodDelete,
		 "/subscription-data/group-data/5g-vn-groups/:externalGroupId",
		 HttpDelete5GVnGroup,
	 },
 
	 {
		 "HttpQueryCoverageRestrictionData",
		 http.MethodGet,
		 "/subscription-data/:ueId/coverage-restriction-data",
		 HttpQueryCoverageRestrictionData,
	 },
 
	 {
		 "HttpRemoveAmfSubscriptionsInfo",
		 http.MethodDelete,
		 "/subscription-data/:ueId/context-data/ee-subscriptions/:subsId/amf-subscriptions",
		 HttpRemoveAmfSubscriptionsInfo,
	 },
 
	 {
		 "HttpQueryEEData",
		 http.MethodGet,
		 "/subscription-data/:ueId/ee-profile-data",
		 HttpQueryEEData,
	 },
 
	 {
		 "HttpQueryGroupEEData",
		 http.MethodGet,
		 "/subscription-data/group-data/:ueGroupId/ee-profile-data",
		 HttpQueryGroupEEData,
	 },
 
	 {
		 "HttpModifyEeGroupSubscription",
		 http.MethodPatch,
		 "/subscription-data/group-data/:ueGroupId/ee-subscriptions/:subsId",
		 HttpModifyEeGroupSubscription,
	 },
 
	 {
		 "HttpQueryEeGroupSubscription",
		 http.MethodGet,
		 "/subscription-data/group-data/:ueGroupId/ee-subscriptions/:subsId",
		 HttpQueryEeGroupSubscription,
	 },
 
	 {
		 "HttpRemoveEeGroupSubscriptions",
		 http.MethodDelete,
		 "/subscription-data/group-data/:ueGroupId/ee-subscriptions/:subsId",
		 HttpRemoveEeGroupSubscriptions,
	 },
 
	 {
		 "HttpUpdateEeGroupSubscriptions",
		 http.MethodPut,
		 "/subscription-data/group-data/:ueGroupId/ee-subscriptions/:subsId",
		 HttpUpdateEeGroupSubscriptions,
	 },
 
	 {
		 "HttpCreateEeGroupSubscriptions",
		 http.MethodPost,
		 "/subscription-data/group-data/:ueGroupId/ee-subscriptions",
		 HttpCreateEeGroupSubscriptions,
	 },
 
	 {
		 "HttpQueryEeGroupSubscriptions",
		 http.MethodGet,
		 "/subscription-data/group-data/:ueGroupId/ee-subscriptions",
		 HttpQueryEeGroupSubscriptions,
	 },
 
	 {
		 "HttpModifyEesubscription",
		 http.MethodPatch,
		 "/subscription-data/:ueId/context-data/ee-subscriptions/:subsId",
		 HttpModifyEesubscription,
	 },
 
	 {
		 "HttpQueryeeSubscription",
		 http.MethodGet,
		 "/subscription-data/:ueId/context-data/ee-subscriptions/:subsId",
		 HttpQueryeeSubscription,
	 },
 
	 {
		 "HttpRemoveeeSubscriptions",
		 http.MethodDelete,
		 "/subscription-data/:ueId/context-data/ee-subscriptions/:subsId",
		 HttpRemoveeeSubscriptions,
	 },
 
	 {
		 "HttpUpdateEesubscriptions",
		 http.MethodPut,
		 "/subscription-data/:ueId/context-data/ee-subscriptions/:subsId",
		 HttpUpdateEesubscriptions,
	 },
 
	 {
		 "HttpCreateEeSubscriptions",
		 http.MethodPost,
		 "/subscription-data/:ueId/context-data/ee-subscriptions",
		 HttpCreateEeSubscriptions,
	 },
 
	 {
		 "HttpQueryeesubscriptions",
		 http.MethodGet,
		 "/subscription-data/:ueId/context-data/ee-subscriptions",
		 HttpQueryeesubscriptions,
	 },
 
	 {
		 "HttpCreateIndividualExposureDataSubscription",
		 http.MethodPost,
		 "/exposure-data/subs-to-notify",
		 HttpCreateIndividualExposureDataSubscription,
	 },
 
	 {
		 "HttpGetGroupIdentifiers",
		 http.MethodGet,
		 "/subscription-data/group-data/group-identifiers",
		 HttpGetGroupIdentifiers,
	 },
 
	 {
		 "HttpCreateHSSSubscriptions",
		 http.MethodPut,
		 "/subscription-data/:ueId/context-data/ee-subscriptions/:subsId/hss-subscriptions",
		 HttpCreateHSSSubscriptions,
	 },
 
	 {
		 "HttpGetHssSubscriptionInfo",
		 http.MethodGet,
		 "/subscription-data/:ueId/context-data/ee-subscriptions/:subsId/hss-subscriptions",
		 HttpGetHssSubscriptionInfo,
	 },
 
	 {
		 "HttpModifyHssSubscriptionInfo",
		 http.MethodPatch,
		 "/subscription-data/:ueId/context-data/ee-subscriptions/:subsId/hss-subscriptions",
		 HttpModifyHssSubscriptionInfo,
	 },
 
	 {
		 "HttpRemoveHssSubscriptionsInfo",
		 http.MethodDelete,
		 "/subscription-data/:ueId/context-data/ee-subscriptions/:subsId/hss-subscriptions",
		 HttpRemoveHssSubscriptionsInfo,
	 },
 
	 {
		 "HttpCreateHSSSDMSubscriptions",
		 http.MethodPut,
		 "/subscription-data/:ueId/context-data/sdm-subscriptions/:subsId/hss-sdm-subscriptions",
		 HttpCreateHSSSDMSubscriptions,
	 },
 
	 {
		 "HttpGetHssSDMSubscriptionInfo",
		 http.MethodGet,
		 "/subscription-data/:ueId/context-data/sdm-subscriptions/:subsId/hss-sdm-subscriptions",
		 HttpGetHssSDMSubscriptionInfo,
	 },
 
	 {
		 "HttpModifyHssSDMSubscriptionInfo",
		 http.MethodPatch,
		 "/subscription-data/:ueId/context-data/sdm-subscriptions/:subsId/hss-sdm-subscriptions",
		 HttpModifyHssSDMSubscriptionInfo,
	 },
 
	 {
		 "HttpRemoveHssSDMSubscriptionsInfo",
		 http.MethodDelete,
		 "/subscription-data/:ueId/context-data/sdm-subscriptions/:subsId/hss-sdm-subscriptions",
		 HttpRemoveHssSDMSubscriptionsInfo,
	 },
 
	 {
		 "HttpCreateIpSmGwContext",
		 http.MethodPut,
		 "/subscription-data/:ueId/context-data/ip-sm-gw",
		 HttpCreateIpSmGwContext,
	 },
 
	 {
		 "HttpDeleteIpSmGwContext",
		 http.MethodDelete,
		 "/subscription-data/:ueId/context-data/ip-sm-gw",
		 HttpDeleteIpSmGwContext,
	 },
 
	 {
		 "HttpModifyIpSmGwContext",
		 http.MethodPatch,
		 "/subscription-data/:ueId/context-data/ip-sm-gw",
		 HttpModifyIpSmGwContext,
	 },
 
	 {
		 "HttpQueryIpSmGwContext",
		 http.MethodGet,
		 "/subscription-data/:ueId/context-data/ip-sm-gw",
		 HttpQueryIpSmGwContext,
	 },
 
	 {
		 "HttpReadIPTVCongifurationData",
		 http.MethodGet,
		 "/application-data/iptvConfigData",
		 HttpReadIPTVCongifurationData,
	 },
 
	 {
		 "HttpDeleteIndividualApplicationDataSubscription",
		 http.MethodDelete,
		 "/application-data/subs-to-notify/:subsId",
		 HttpDeleteIndividualApplicationDataSubscription,
	 },
 
	 {
		 "HttpReadIndividualApplicationDataSubscription",
		 http.MethodGet,
		 "/application-data/subs-to-notify/:subsId",
		 HttpReadIndividualApplicationDataSubscription,
	 },
 
	 {
		 "HttpReplaceIndividualApplicationDataSubscription",
		 http.MethodPut,
		 "/application-data/subs-to-notify/:subsId",
		 HttpReplaceIndividualApplicationDataSubscription,
	 },
 
	 {
		 "HttpCreateIndividualAppliedBdtPolicyData",
		 http.MethodPut,
		 "/application-data/bdtPolicyData/:bdtPolicyId",
		 HttpCreateIndividualAppliedBdtPolicyData,
	 },
 
	 {
		 "HttpDeleteIndividualAppliedBdtPolicyData",
		 http.MethodDelete,
		 "/application-data/bdtPolicyData/:bdtPolicyId",
		 HttpDeleteIndividualAppliedBdtPolicyData,
	 },
 
	 {
		 "HttpUpdateIndividualAppliedBdtPolicyData",
		 http.MethodPatch,
		 "/application-data/bdtPolicyData/:bdtPolicyId",
		 HttpUpdateIndividualAppliedBdtPolicyData,
	 },
 
	 {
		 "HttpDeleteIndividualAuthenticationStatus",
		 http.MethodDelete,
		 "/subscription-data/:ueId/authentication-data/authentication-status/:servingNetworkName",
		 HttpDeleteIndividualAuthenticationStatus,
	 },
 
	 {
		 "HttpQueryIndividualAuthenticationStatus",
		 http.MethodGet,
		 "/subscription-data/:ueId/authentication-data/authentication-status/:servingNetworkName",
		 HttpQueryIndividualAuthenticationStatus,
	 },
 
	 {
		 "HttpCreateIndividualAuthenticationStatus",
		 http.MethodPut,
		 "/subscription-data/:ueId/authentication-data/authentication-status/:servingNetworkName",
		 HttpCreateIndividualAuthenticationStatus,
	 },
 
	 {
		 "HttpCreateIndividualBdtData",
		 http.MethodPut,
		 "/policy-data/bdt-data/:bdtReferenceId",
		 HttpCreateIndividualBdtData,
	 },
 
	 {
		 "HttpDeleteIndividualBdtData",
		 http.MethodDelete,
		 "/policy-data/bdt-data/:bdtReferenceId",
		 HttpDeleteIndividualBdtData,
	 },
 
	 {
		 "HttpReadIndividualBdtData",
		 http.MethodGet,
		 "/policy-data/bdt-data/:bdtReferenceId",
		 HttpReadIndividualBdtData,
	 },
 
	 {
		 "HttpUpdateIndividualBdtData",
		 http.MethodPatch,
		 "/policy-data/bdt-data/:bdtReferenceId",
		 HttpUpdateIndividualBdtData,
	 },
 
	 {
		 "HttpDeleteIndividualExposureDataSubscription",
		 http.MethodDelete,
		 "/exposure-data/subs-to-notify/:subId",
		 HttpDeleteIndividualExposureDataSubscription,
	 },
 
	 {
		 "HttpReplaceIndividualExposureDataSubscription",
		 http.MethodPut,
		 "/exposure-data/subs-to-notify/:subId",
		 HttpReplaceIndividualExposureDataSubscription,
	 },
 
	 {
		 "HttpPartialReplaceIndividualIPTVConfigurationData",
		 http.MethodPatch,
		 "/application-data/iptvConfigData/:configurationId",
		 HttpPartialReplaceIndividualIPTVConfigurationData,
	 },
 
	 {
		 "HttpCreateOrReplaceIndividualIPTVConfigurationData",
		 http.MethodPut,
		 "/application-data/iptvConfigData/:configurationId",
		 HttpCreateOrReplaceIndividualIPTVConfigurationData,
	 },
 
	 {
		 "HttpDeleteIndividualIPTVConfigurationData",
		 http.MethodDelete,
		 "/application-data/iptvConfigData/:configurationId",
		 HttpDeleteIndividualIPTVConfigurationData,
	 },
 
	 {
		 "HttpCreateOrReplaceIndividualInfluenceData",
		 http.MethodPut,
		 "/application-data/influenceData/:influenceId",
		 HttpCreateOrReplaceIndividualInfluenceData,
	 },
 
	 {
		 "HttpDeleteIndividualInfluenceData",
		 http.MethodDelete,
		 "/application-data/influenceData/:influenceId",
		 HttpDeleteIndividualInfluenceData,
	 },
 
	 {
		 "HttpUpdateIndividualInfluenceData",
		 http.MethodPatch,
		 "/application-data/influenceData/:influenceId",
		 HttpUpdateIndividualInfluenceData,
	 },
 
	 {
		 "HttpDeleteIndividualInfluenceDataSubscription",
		 http.MethodDelete,
		 "/application-data/influenceData/subs-to-notify/:subscriptionId",
		 HttpDeleteIndividualInfluenceDataSubscription,
	 },
 
	 {
		 "HttpReadIndividualInfluenceDataSubscription",
		 http.MethodGet,
		 "/application-data/influenceData/subs-to-notify/:subscriptionId",
		 HttpReadIndividualInfluenceDataSubscription,
	 },
 
	 {
		 "HttpReplaceIndividualInfluenceDataSubscription",
		 http.MethodPut,
		 "/application-data/influenceData/subs-to-notify/:subscriptionId",
		 HttpReplaceIndividualInfluenceDataSubscription,
	 },
 
	 {
		 "HttpCreateOrReplaceIndividualPFDData",
		 http.MethodPut,
		 "/application-data/pfds/:appId",
		 HttpCreateOrReplaceIndividualPFDData,
	 },
 
	 {
		 "HttpDeleteIndividualPFDData",
		 http.MethodDelete,
		 "/application-data/pfds/:appId",
		 HttpDeleteIndividualPFDData,
	 },
 
	 {
		 "HttpReadIndividualPFDData",
		 http.MethodGet,
		 "/application-data/pfds/:appId",
		 HttpReadIndividualPFDData,
	 },
 
	 {
		 "HttpDeleteIndividualPolicyDataSubscription",
		 http.MethodDelete,
		 "/policy-data/subs-to-notify/:subsId",
		 HttpDeleteIndividualPolicyDataSubscription,
	 },
 
	 {
		 "HttpReplaceIndividualPolicyDataSubscription",
		 http.MethodPut,
		 "/policy-data/subs-to-notify/:subsId",
		 HttpReplaceIndividualPolicyDataSubscription,
	 },
 
	 {
		 "HttpCreateOrReplaceServiceParameterData",
		 http.MethodPut,
		 "/application-data/serviceParamData/:serviceParamId",
		 HttpCreateOrReplaceServiceParameterData,
	 },
 
	 {
		 "HttpDeleteIndividualServiceParameterData",
		 http.MethodDelete,
		 "/application-data/serviceParamData/:serviceParamId",
		 HttpDeleteIndividualServiceParameterData,
	 },
 
	 {
		 "HttpUpdateIndividualServiceParameterData",
		 http.MethodPatch,
		 "/application-data/serviceParamData/:serviceParamId",
		 HttpUpdateIndividualServiceParameterData,
	 },
 
	 {
		 "HttpReadInfluenceData",
		 http.MethodGet,
		 "/application-data/influenceData",
		 HttpReadInfluenceData,
	 },
 
	 {
		 "HttpCreateIndividualInfluenceDataSubscription",
		 http.MethodPost,
		 "/application-data/influenceData/subs-to-notify",
		 HttpCreateIndividualInfluenceDataSubscription,
	 },
 
	 {
		 "HttpReadInfluenceDataSubscriptions",
		 http.MethodGet,
		 "/application-data/influenceData/subs-to-notify",
		 HttpReadInfluenceDataSubscriptions,
	 },
 
	 {
		 "HttpQueryLcsBcaData",
		 http.MethodGet,
		 "/subscription-data/:ueId/:servingPlmnId/provisioned-data/lcs-bca-data",
		 HttpQueryLcsBcaData,
	 },
 
	 {
		 "HttpQueryLcsMoData",
		 http.MethodGet,
		 "/subscription-data/:ueId/lcs-mo-data",
		 HttpQueryLcsMoData,
	 },
 
	 {
		 "HttpQueryLcsPrivacyData",
		 http.MethodGet,
		 "/subscription-data/:ueId/lcs-privacy-data",
		 HttpQueryLcsPrivacyData,
	 },
 
	 {
		 "HttpCreateMessageWaitingData",
		 http.MethodPut,
		 "/subscription-data/:ueId/context-data/mwd",
		 HttpCreateMessageWaitingData,
	 },
 
	 {
		 "HttpDeleteMessageWaitingData",
		 http.MethodDelete,
		 "/subscription-data/:ueId/context-data/mwd",
		 HttpDeleteMessageWaitingData,
	 },
 
	 {
		 "HttpModifyMessageWaitingData",
		 http.MethodPatch,
		 "/subscription-data/:ueId/context-data/mwd",
		 HttpModifyMessageWaitingData,
	 },
 
	 {
		 "HttpQueryMessageWaitingData",
		 http.MethodGet,
		 "/subscription-data/:ueId/context-data/mwd",
		 HttpQueryMessageWaitingData,
	 },
 
	 {
		 "HttpModify5GVnGroup",
		 http.MethodPatch,
		 "/subscription-data/group-data/5g-vn-groups/:externalGroupId",
		 HttpModify5GVnGroup,
	 },
 
	 {
		 "HttpQueryNssaiAck",
		 http.MethodGet,
		 "/subscription-data/:ueId/ue-update-confirmation-data/subscribed-snssais",
		 HttpQueryNssaiAck,
	 },
 
	 {
		 "HttpCreateNSSAIUpdateAck",
		 http.MethodPut,
		 "/subscription-data/:ueId/ue-update-confirmation-data/subscribed-snssais",
		 HttpCreateNSSAIUpdateAck,
	 },
 
	 {
		 "HttpModifyOperSpecData",
		 http.MethodPatch,
		 "/subscription-data/:ueId/operator-specific-data",
		 HttpModifyOperSpecData,
	 },
 
	 {
		 "HttpQueryOperSpecData",
		 http.MethodGet,
		 "/subscription-data/:ueId/operator-specific-data",
		 HttpQueryOperSpecData,
	 },
 
	 {
		 "HttpReadOperatorSpecificData",
		 http.MethodGet,
		 "/policy-data/ues/:ueId/operator-specific-data",
		 HttpReadOperatorSpecificData,
	 },
 
	 {
		 "HttpReplaceOperatorSpecificData",
		 http.MethodPut,
		 "/policy-data/ues/:ueId/operator-specific-data",
		 HttpReplaceOperatorSpecificData,
	 },
 
	 {
		 "HttpUpdateOperatorSpecificData",
		 http.MethodPatch,
		 "/policy-data/ues/:ueId/operator-specific-data",
		 HttpUpdateOperatorSpecificData,
	 },
 
	 {
		 "HttpReadPFDData",
		 http.MethodGet,
		 "/application-data/pfds",
		 HttpReadPFDData,
	 },
 
	 {
		 "HttpGetppData",
		 http.MethodGet,
		 "/subscription-data/:ueId/pp-data",
		 HttpGetppData,
	 },
 
	 {
		 "HttpQueryPPData",
		 http.MethodGet,
		 "/subscription-data/:ueId/pp-profile-data",
		 HttpQueryPPData,
	 },
 
	 {
		 "HttpQuery5GVNGroupPPData",
		 http.MethodGet,
		 "/subscription-data/group-data/5g-vn-groups/pp-profile-data",
		 HttpQuery5GVNGroupPPData,
	 },
 
	 {
		 "HttpCreateOrReplaceSessionManagementData",
		 http.MethodPut,
		 "/exposure-data/:ueId/session-management-data/:pduSessionId",
		 HttpCreateOrReplaceSessionManagementData,
	 },
 
	 {
		 "HttpDeleteSessionManagementData",
		 http.MethodDelete,
		 "/exposure-data/:ueId/session-management-data/:pduSessionId",
		 HttpDeleteSessionManagementData,
	 },
 
	 {
		 "HttpQuerySessionManagementData",
		 http.MethodGet,
		 "/exposure-data/:ueId/session-management-data/:pduSessionId",
		 HttpQuerySessionManagementData,
	 },
 
	 {
		 "HttpReadPlmnUePolicySet",
		 http.MethodGet,
		 "/policy-data/plmns/:plmnId/ue-policy-set",
		 HttpReadPlmnUePolicySet,
	 },
 
	 {
		 "HttpCreateIndividualPolicyDataSubscription",
		 http.MethodPost,
		 "/policy-data/subs-to-notify",
		 HttpCreateIndividualPolicyDataSubscription,
	 },
 
	 {
		 "HttpQueryProvisionedData",
		 http.MethodGet,
		 "/subscription-data/:ueId/:servingPlmnId/provisioned-data",
		 HttpQueryProvisionedData,
	 },
 
	 {
		 "HttpModifyPpData",
		 http.MethodPatch,
		 "/subscription-data/:ueId/pp-data",
		 HttpModifyPpData,
	 },
 
	 {
		 "HttpGet5GVnGroupConfiguration",
		 http.MethodGet,
		 "/subscription-data/group-data/5g-vn-groups/:externalGroupId",
		 HttpGet5GVnGroupConfiguration,
	 },
 
	 {
		 "HttpGetAmfSubscriptionInfo",
		 http.MethodGet,
		 "/subscription-data/:ueId/context-data/ee-subscriptions/:subsId/amf-subscriptions",
		 HttpGetAmfSubscriptionInfo,
	 },
 
	 {
		 "HttpGetIdentityData",
		 http.MethodGet,
		 "/subscription-data/:ueId/identity-data",
		 HttpGetIdentityData,
	 },
 
	 {
		 "HttpGetNiddAuData",
		 http.MethodGet,
		 "/subscription-data/:ueId/nidd-authorization-data",
		 HttpGetNiddAuData,
	 },
 
	 {
		 "HttpGetOdbData",
		 http.MethodGet,
		 "/subscription-data/:ueId/operator-determined-barring-data",
		 HttpGetOdbData,
	 },
 
	 {
		 "HttpGetIndividualSharedData",
		 http.MethodGet,
		 "/subscription-data/shared-data/:sharedDataId",
		 HttpGetIndividualSharedData,
	 },
 
	 {
		 "HttpGetSharedData",
		 http.MethodGet,
		 "/subscription-data/shared-data",
		 HttpGetSharedData,
	 },
 
	 {
		 "HttpModifysdmSubscription",
		 http.MethodPatch,
		 "/subscription-data/:ueId/context-data/sdm-subscriptions/:subsId",
		 HttpModifysdmSubscription,
	 },
 
	 {
		 "HttpQuerysdmSubscription",
		 http.MethodGet,
		 "/subscription-data/:ueId/context-data/sdm-subscriptions/:subsId",
		 HttpQuerysdmSubscription,
	 },
 
	 {
		 "HttpRemovesdmSubscriptions",
		 http.MethodDelete,
		 "/subscription-data/:ueId/context-data/sdm-subscriptions/:subsId",
		 HttpRemovesdmSubscriptions,
	 },
 
	 {
		 "HttpUpdatesdmsubscriptions",
		 http.MethodPut,
		 "/subscription-data/:ueId/context-data/sdm-subscriptions/:subsId",
		 HttpUpdatesdmsubscriptions,
	 },
 
	 {
		 "HttpCreateSdmSubscriptions",
		 http.MethodPost,
		 "/subscription-data/:ueId/context-data/sdm-subscriptions",
		 HttpCreateSdmSubscriptions,
	 },
 
	 {
		 "HttpQuerysdmsubscriptions",
		 http.MethodGet,
		 "/subscription-data/:ueId/context-data/sdm-subscriptions",
		 HttpQuerysdmsubscriptions,
	 },
 
	 {
		 "HttpCreateSMFSubscriptions",
		 http.MethodPut,
		 "/subscription-data/:ueId/context-data/ee-subscriptions/:subsId/smf-subscriptions",
		 HttpCreateSMFSubscriptions,
	 },
 
	 {
		 "HttpGetSmfSubscriptionInfo",
		 http.MethodGet,
		 "/subscription-data/:ueId/context-data/ee-subscriptions/:subsId/smf-subscriptions",
		 HttpGetSmfSubscriptionInfo,
	 },
 
	 {
		 "HttpModifySmfSubscriptionInfo",
		 http.MethodPatch,
		 "/subscription-data/:ueId/context-data/ee-subscriptions/:subsId/smf-subscriptions",
		 HttpModifySmfSubscriptionInfo,
	 },
 
	 {
		 "HttpRemoveSmfSubscriptionsInfo",
		 http.MethodDelete,
		 "/subscription-data/:ueId/context-data/ee-subscriptions/:subsId/smf-subscriptions",
		 HttpRemoveSmfSubscriptionsInfo,
	 },
 
	 {
		 "HttpCreateSmfContextNon3gpp",
		 http.MethodPut,
		 "/subscription-data/:ueId/context-data/smf-registrations/:pduSessionId",
		 HttpCreateSmfContextNon3gpp,
	 },
 
	 {
		 "HttpDeleteSmfContext",
		 http.MethodDelete,
		 "/subscription-data/:ueId/context-data/smf-registrations/:pduSessionId",
		 HttpDeleteSmfContext,
	 },
 
	 {
		 "HttpQuerySmfRegistration",
		 http.MethodGet,
		 "/subscription-data/:ueId/context-data/smf-registrations/:pduSessionId",
		 HttpQuerySmfRegistration,
	 },
 
	 {
		 "HttpQuerySmfRegList",
		 http.MethodGet,
		 "/subscription-data/:ueId/context-data/smf-registrations",
		 HttpQuerySmfRegList,
	 },
 
	 {
		 "HttpQuerySmfSelectData",
		 http.MethodGet,
		 "/subscription-data/:ueId/:servingPlmnId/provisioned-data/smf-selection-subscription-data",
		 HttpQuerySmfSelectData,
	 },
 
	 {
		 "HttpCreateSmsfContext3gpp",
		 http.MethodPut,
		 "/subscription-data/:ueId/context-data/smsf-3gpp-access",
		 HttpCreateSmsfContext3gpp,
	 },
 
	 {
		 "HttpDeleteSmsfContext3gpp",
		 http.MethodDelete,
		 "/subscription-data/:ueId/context-data/smsf-3gpp-access",
		 HttpDeleteSmsfContext3gpp,
	 },
 
	 {
		 "HttpQuerySmsfContext3gpp",
		 http.MethodGet,
		 "/subscription-data/:ueId/context-data/smsf-3gpp-access",
		 HttpQuerySmsfContext3gpp,
	 },
 
	 {
		 "HttpCreateSmsfContextNon3gpp",
		 http.MethodPut,
		 "/subscription-data/:ueId/context-data/smsf-non-3gpp-access",
		 HttpCreateSmsfContextNon3gpp,
	 },
 
	 {
		 "HttpDeleteSmsfContextNon3gpp",
		 http.MethodDelete,
		 "/subscription-data/:ueId/context-data/smsf-non-3gpp-access",
		 HttpDeleteSmsfContextNon3gpp,
	 },
 
	 {
		 "HttpQuerySmsfContextNon3gpp",
		 http.MethodGet,
		 "/subscription-data/:ueId/context-data/smsf-non-3gpp-access",
		 HttpQuerySmsfContextNon3gpp,
	 },
 
	 {
		 "HttpQuerySmsMngData",
		 http.MethodGet,
		 "/subscription-data/:ueId/:servingPlmnId/provisioned-data/sms-mng-data",
		 HttpQuerySmsMngData,
	 },
 
	 {
		 "HttpQuerySmsData",
		 http.MethodGet,
		 "/subscription-data/:ueId/:servingPlmnId/provisioned-data/sms-data",
		 HttpQuerySmsData,
	 },
 
	 {
		 "HttpReadServiceParameterData",
		 http.MethodGet,
		 "/application-data/serviceParamData",
		 HttpReadServiceParameterData,
	 },
 
	 {
		 "HttpReadSessionManagementPolicyData",
		 http.MethodGet,
		 "/policy-data/ues/:ueId/sm-data",
		 HttpReadSessionManagementPolicyData,
	 },
 
	 {
		 "HttpUpdateSessionManagementPolicyData",
		 http.MethodPatch,
		 "/policy-data/ues/:ueId/sm-data",
		 HttpUpdateSessionManagementPolicyData,
	 },
 
	 {
		 "HttpQuerySmData",
		 http.MethodGet,
		 "/subscription-data/:ueId/:servingPlmnId/provisioned-data/sm-data",
		 HttpQuerySmData,
	 },
 
	 {
		 "HttpReadSponsorConnectivityData",
		 http.MethodGet,
		 "/policy-data/sponsor-connectivity-data/:sponsorId",
		 HttpReadSponsorConnectivityData,
	 },
 
	 {
		 "HttpQuerySubsToNotify",
		 http.MethodGet,
		 "/subscription-data/subs-to-notify",
		 HttpQuerySubsToNotify,
	 },
 
	 {
		 "HttpRemoveMultipleSubscriptionDataSubscriptions",
		 http.MethodDelete,
		 "/subscription-data/subs-to-notify",
		 HttpRemoveMultipleSubscriptionDataSubscriptions,
	 },
 
	 {
		 "HttpSubscriptionDataSubscriptions",
		 http.MethodPost,
		 "/subscription-data/subs-to-notify",
		 HttpSubscriptionDataSubscriptions,
	 },
 
	 {
		 "HttpModifysubscriptionDataSubscription",
		 http.MethodPatch,
		 "/subscription-data/subs-to-notify/:subsId",
		 HttpModifysubscriptionDataSubscription,
	 },
 
	 {
		 "HttpQuerySubscriptionDataSubscriptions",
		 http.MethodGet,
		 "/subscription-data/subs-to-notify/:subsId",
		 HttpQuerySubscriptionDataSubscriptions,
	 },
 
	 {
		 "HttpRemovesubscriptionDataSubscriptions",
		 http.MethodDelete,
		 "/subscription-data/subs-to-notify/:subsId",
		 HttpRemovesubscriptionDataSubscriptions,
	 },
 
	 {
		 "HttpQueryTraceData",
		 http.MethodGet,
		 "/subscription-data/:ueId/:servingPlmnId/provisioned-data/trace-data",
		 HttpQueryTraceData,
	 },
 
	 {
		 "HttpCreateOrReplaceUEPolicySet",
		 http.MethodPut,
		 "/policy-data/ues/:ueId/ue-policy-set",
		 HttpCreateOrReplaceUEPolicySet,
	 },
 
	 {
		 "HttpReadUEPolicySet",
		 http.MethodGet,
		 "/policy-data/ues/:ueId/ue-policy-set",
		 HttpReadUEPolicySet,
	 },
 
	 {
		 "HttpUpdateUEPolicySet",
		 http.MethodPatch,
		 "/policy-data/ues/:ueId/ue-policy-set",
		 HttpUpdateUEPolicySet,
	 },
 
	 {
		 "HttpQueryUeLocation",
		 http.MethodGet,
		 "/subscription-data/:ueId/context-data/location",
		 HttpQueryUeLocation,
	 },
 
	 {
		 "HttpCreateUsageMonitoringResource",
		 http.MethodPut,
		 "/policy-data/ues/:ueId/sm-data/:usageMonId",
		 HttpCreateUsageMonitoringResource,
	 },
 
	 {
		 "HttpDeleteUsageMonitoringInformation",
		 http.MethodDelete,
		 "/policy-data/ues/:ueId/sm-data/:usageMonId",
		 HttpDeleteUsageMonitoringInformation,
	 },
 
	 {
		 "HttpReadUsageMonitoringInformation",
		 http.MethodGet,
		 "/policy-data/ues/:ueId/sm-data/:usageMonId",
		 HttpReadUsageMonitoringInformation,
	 },
 
	 {
		 "HttpQueryV2xData",
		 http.MethodGet,
		 "/subscription-data/:ueId/v2x-data",
		 HttpQueryV2xData,
	 },
 }
 